GLEW_INCLUDE = /opt/local/include
GLEW_LIB = /opt/local/lib

hello-gl: hello-gl.o util.o
	gcc -o hello-gl $^ -framework GLUT -framework OpenGL -L$(GLEW_LIB) -lGLEW

.c.o:
	gcc -c -o $@ $< -I$(GLEW_INCLUDE)

clean:
	rm -f hello-gl hello-gl.o util.o 

